day_01:
	python solutions/day_01_01.py solutions/inputs/day_01_01.txt
	python solutions/day_01_02.py solutions/inputs/day_01_01.txt

day_02:
	python solutions/day_02_01.py solutions/inputs/day_02_01.txt
	python solutions/day_02_02.py solutions/inputs/day_02_01.txt
